#!/usr/bin/env python3
"""
C.O.R.A Self-Modification System
Create and execute temporary scripts for dynamic behavior

Per ARCHITECTURE.md v2.2.0:
- temp_scripts/ directory for one-shot scripts
- create_script(name, code) - creates executable script
- run_script(name) - runs and optionally deletes
- list_scripts() - shows available temp scripts
- cleanup_scripts() - removes old scripts
"""

import os
import sys
import subprocess
import tempfile
import shutil
from pathlib import Path
from datetime import datetime, timedelta
from typing import Optional, Dict, Any, List
import json

# Project paths
PROJECT_DIR = Path(__file__).parent.parent
TEMP_SCRIPTS_DIR = PROJECT_DIR / 'temp_scripts'
SCRIPT_INDEX = TEMP_SCRIPTS_DIR / 'index.json'


def _ensure_temp_dir():
    """Ensure temp_scripts directory exists."""
    TEMP_SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    if not SCRIPT_INDEX.exists():
        _save_index({})


def _load_index() -> Dict[str, Any]:
    """Load the script index."""
    _ensure_temp_dir()
    if SCRIPT_INDEX.exists():
        try:
            with open(SCRIPT_INDEX) as f:
                return json.load(f)
        except Exception:
            return {}
    return {}


def _save_index(index: Dict[str, Any]):
    """Save the script index."""
    _ensure_temp_dir()
    with open(SCRIPT_INDEX, 'w') as f:
        json.dump(index, f, indent=2, default=str)


def create_script(
    name: str,
    code: str,
    description: str = "",
    auto_delete: bool = True,
    max_age_hours: int = 24
) -> Dict[str, Any]:
    """Create a temporary Python script.

    Args:
        name: Script name (without .py extension)
        code: Python code to execute
        description: Optional description
        auto_delete: Delete after execution
        max_age_hours: Delete if older than this

    Returns:
        Dict with success status and script path
    """
    _ensure_temp_dir()

    # Sanitize name
    safe_name = "".join(c for c in name if c.isalnum() or c in '_-')
    if not safe_name:
        return {"success": False, "error": "Invalid script name"}

    script_path = TEMP_SCRIPTS_DIR / f"{safe_name}.py"

    try:
        # Add standard header
        full_code = f'''#!/usr/bin/env python3
"""
Temporary Script: {safe_name}
Created: {datetime.now().isoformat()}
Description: {description}

This script was auto-generated by C.O.R.A self-modification system.
"""

import sys
sys.path.insert(0, r'{PROJECT_DIR}')

{code}
'''
        with open(script_path, 'w') as f:
            f.write(full_code)

        # Update index
        index = _load_index()
        index[safe_name] = {
            'path': str(script_path),
            'created': datetime.now().isoformat(),
            'description': description,
            'auto_delete': auto_delete,
            'max_age_hours': max_age_hours,
            'runs': 0
        }
        _save_index(index)

        return {
            "success": True,
            "name": safe_name,
            "path": str(script_path),
            "auto_delete": auto_delete
        }

    except Exception as e:
        return {"success": False, "error": str(e)}


def run_script(
    name: str,
    args: List[str] = None,
    capture_output: bool = True,
    timeout: int = 30,
    delete_after: bool = None
) -> Dict[str, Any]:
    """Run a temporary script.

    Args:
        name: Script name
        args: Command line arguments
        capture_output: Capture stdout/stderr
        timeout: Execution timeout in seconds
        delete_after: Override auto_delete setting

    Returns:
        Dict with execution results
    """
    index = _load_index()
    safe_name = "".join(c for c in name if c.isalnum() or c in '_-')

    if safe_name not in index:
        return {"success": False, "error": f"Script '{name}' not found"}

    script_info = index[safe_name]
    script_path = Path(script_info['path'])

    if not script_path.exists():
        return {"success": False, "error": f"Script file missing: {script_path}"}

    try:
        cmd = [sys.executable, str(script_path)]
        if args:
            cmd.extend(args)

        result = subprocess.run(
            cmd,
            capture_output=capture_output,
            text=True,
            timeout=timeout,
            cwd=str(PROJECT_DIR)
        )

        # Update run count
        script_info['runs'] = script_info.get('runs', 0) + 1
        script_info['last_run'] = datetime.now().isoformat()
        index[safe_name] = script_info
        _save_index(index)

        # Check if should delete
        should_delete = delete_after if delete_after is not None else script_info.get('auto_delete', True)

        if should_delete:
            delete_script(safe_name)

        return {
            "success": result.returncode == 0,
            "returncode": result.returncode,
            "stdout": result.stdout if capture_output else None,
            "stderr": result.stderr if capture_output else None,
            "deleted": should_delete
        }

    except subprocess.TimeoutExpired:
        return {"success": False, "error": f"Script timed out after {timeout}s"}
    except Exception as e:
        return {"success": False, "error": str(e)}


def delete_script(name: str) -> bool:
    """Delete a temporary script.

    Args:
        name: Script name

    Returns:
        bool: True if deleted
    """
    index = _load_index()
    safe_name = "".join(c for c in name if c.isalnum() or c in '_-')

    if safe_name not in index:
        return False

    script_path = Path(index[safe_name]['path'])
    if script_path.exists():
        script_path.unlink()

    del index[safe_name]
    _save_index(index)
    return True


def list_scripts() -> List[Dict[str, Any]]:
    """List all temporary scripts.

    Returns:
        List of script info dicts
    """
    index = _load_index()
    scripts = []

    for name, info in index.items():
        script_path = Path(info['path'])
        scripts.append({
            'name': name,
            'exists': script_path.exists(),
            'created': info.get('created'),
            'description': info.get('description', ''),
            'runs': info.get('runs', 0),
            'auto_delete': info.get('auto_delete', True)
        })

    return scripts


def cleanup_scripts(max_age_hours: int = None) -> Dict[str, Any]:
    """Remove old temporary scripts.

    Args:
        max_age_hours: Override default max age

    Returns:
        Dict with cleanup stats
    """
    index = _load_index()
    deleted = []
    errors = []

    for name, info in list(index.items()):
        script_path = Path(info['path'])
        script_age = max_age_hours or info.get('max_age_hours', 24)

        # Check if script file exists
        if not script_path.exists():
            deleted.append(name)
            del index[name]
            continue

        # Check age
        try:
            created = datetime.fromisoformat(info.get('created', datetime.now().isoformat()))
            age = datetime.now() - created

            if age > timedelta(hours=script_age):
                script_path.unlink()
                deleted.append(name)
                del index[name]
        except Exception as e:
            errors.append(f"{name}: {e}")

    _save_index(index)

    return {
        "deleted": deleted,
        "deleted_count": len(deleted),
        "errors": errors
    }


def create_and_run(
    code: str,
    name: str = None,
    description: str = "One-shot script",
    timeout: int = 30
) -> Dict[str, Any]:
    """Create and immediately run a script.

    Args:
        code: Python code to execute
        name: Optional script name (auto-generated if not provided)
        description: Script description
        timeout: Execution timeout

    Returns:
        Dict with execution results
    """
    if not name:
        name = f"oneshot_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    create_result = create_script(
        name=name,
        code=code,
        description=description,
        auto_delete=True
    )

    if not create_result.get('success'):
        return create_result

    return run_script(name, timeout=timeout)


def get_script_content(name: str) -> Optional[str]:
    """Get the content of a temporary script.

    Args:
        name: Script name

    Returns:
        Script content or None
    """
    index = _load_index()
    safe_name = "".join(c for c in name if c.isalnum() or c in '_-')

    if safe_name not in index:
        return None

    script_path = Path(index[safe_name]['path'])
    if not script_path.exists():
        return None

    return script_path.read_text()


if __name__ == "__main__":
    print("=== CORA Self-Modification System Test ===")

    # Test creating a script
    print("\n1. Creating test script...")
    result = create_script(
        name="test_hello",
        code='print("Hello from temp script!")',
        description="Test script",
        auto_delete=False
    )
    print(f"   Created: {result}")

    # Test listing scripts
    print("\n2. Listing scripts...")
    scripts = list_scripts()
    for s in scripts:
        print(f"   - {s['name']}: {s['description']}")

    # Test running script
    print("\n3. Running script...")
    result = run_script("test_hello", delete_after=False)
    print(f"   Result: {result}")

    # Test create and run
    print("\n4. Create and run one-shot...")
    result = create_and_run(
        code='import platform; print(f"Running on {platform.system()}")',
        description="Platform check"
    )
    print(f"   Result: {result}")

    # Cleanup
    print("\n5. Cleaning up...")
    delete_script("test_hello")
    cleanup = cleanup_scripts()
    print(f"   Cleanup: {cleanup}")

    print("\n=== Test Complete ===")
